### ISSUE TITLE
getting error in extension when the dialog opens

### ISSUE THREAD

**Issue by widox** [bookieio/bookie-firefox#25]
Doing a bit of digging, this appears because of the domain move causing an SSL cert error. The first request it makes returns with

```
bmark.us:443 uses an invalid security certificate.

The certificate is only valid for the following names:
  *.bookie.io, bookie.io  

(Error code: ssl_error_bad_cert_domain)
```

changing the "Bookie url" config to 'bookie.io' fixes the issue.

**Comment by mitechie** [comment]
Thanks for the SSL hint. This was because I setup bmark.us to forward and cut down the config, including the old bmark.us ssl cert. I added it back and so now the redirect is over proper ssl and it seems to no longer error. There's still the issue of getting everyone to update their settings to the new url, but there's no way to force that as it's in custom user config and some users point to other bookie installs. 

Closing this bug on the error for now and will work on releasing an updated default for the extension.
